terms:
  vocabulary:
    dcterms:
      info:
        namespace: "RDF::DC"
        uri: "http://purl.org/dc/terms/"
      # Mandatory Fields
      fields:
        title:
          data_type: text
          facetable: false
          indexed: true
          mandatory: true
          multiple: true
          searchable: true
          stored: true
          display:
            facet:
              show: false
        identifier:
          data_type: text
          facetable: false
          indexed: true
          mandatory: true
          multiple: false
          searchable: true
          stored: true
          display:
            facet:
              show: false
        # Optional Fields

        contributor:
          data_type: text
          facetable: true
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            facet:
              show: false
        creator:
          data_type: text
          facetable: true
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            facet:
              show: true
              label: "Creator"
              sort_key: 2
        date:
          data_type: date
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            facet:
              show: false
        description:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            facet:
              show: false
        # The format/type field confusion needs to be addressed.  For now we are
        # merely reproducing that already problematic configuration that was already
        # in place.
        #
        # See https://www.pivotaltracker.com/n/projects/1025368/stories/113569497
        format:
          data_type: text
          facetable: facetable
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            facet:
              show: false
        language:
          data_type: text
          facetable: true
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            facet:
              show: true
              label: "Language"
              sort_key: 4
        publisher:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            facet:
              show: false
        relation:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            facet:
              show: false
        rights:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            facet:
              show: false
        subject:
          data_type: text
          facetable: true
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            facet:
              show: true
              label: "Subject"
              sort_key: 3
        # The format/type field confusion needs to be addressed.  For now we are
        # merely reproducing that already problematic configuration that was already
        # in place.
        #
        # See https://www.pivotaltracker.com/n/projects/1025368/stories/113569497
        type:
          data_type: text
          facetable: true
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            facet:
              show: true
              label: "Format"
              sort_key: 1

    ichabod:
      info:
        namespace: "NYU::Ichabod::Local"
        uri: "http://library.nyu.edu/data/ichabod#"
      # Optional Fields
      fields:
        addinfolink:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            facet:
              show: false
        addinfotext:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            facet:
              show: false
        data_provider:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            facet:
              show: false
        discoverable:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            facet:
              show: false
        geometry:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            facet:
              show: false
        isbn:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            facet:
              show: false
        location:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: false
          stored: true
          display:
            facet:
              show: false
        repo:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: false
          searchable: false
          stored: true
          display:
            facet:
              show: false
        resource_set:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: false
          searchable: true
          stored: true
          display:
            facet:
              show: false
        subject_spatial:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            facet:
              show: false
        subject_temporal:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            facet:
              show: false

    nyucore:
      info:
        namespace: "NYU::Nyucore"
        uri: "http://harper.bobst.nyu.edu/data/nyucore#"
        # The above uri needs to be changed to something
        # more official
      fields:
        # Optional Fields
        available:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            facet:
              show: false
        citation:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: false
          stored: true
          display:
            facet:
              show: false
        edition:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            facet:
              show: false
        restrictions:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: false
          searchable: false
          stored: true
          display:
            facet:
              show: false
        series:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            facet:
              show: false
        version:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: false
          stored: true
          display:
            facet: false
              show: false
        genre:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            facet: false
              show: false
