terms:
  vocabulary:
    dcterms:
      info:
        namespace: "RDF::DC"
        uri: "http://purl.org/dc/terms/"
      # Mandatory Fields
      fields:
        title:
          data_type: text
          facetable: false
          indexed: true
          mandatory: true
          multiple: true
          searchable: true
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: false
            search_result:
              show: true
              label: "Title"
              sort_key: 1
            detail:
              show: true
              label: "Title"
              sort_key: 1
        identifier:
          data_type: text
          facetable: false
          indexed: true
          mandatory: true
          multiple: false
          searchable: true
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: false
            search_result:
              show: false
            detail:
              show: false
        # Optional Fields

        contributor:
          data_type: text
          facetable: true
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: false
            search_result:
              show: false
            detail:
              show: false
        creator:
          data_type: text
          facetable: true
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: true
              label: "Creator"
              sort_key: 2
            search_result:
              show: false
            detail:
              show: true
              label: "Creator"
              sort_key: 2
        date:
          data_type: date
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: false
            search_result:
              show: false
            detail:
              show: false
        description:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: false
            search_result:
              show: false
            detail:
              show: true
              label: "Description"
              sort_key: 8
        # The format/type field confusion needs to be addressed.  For now we are
        # merely reproducing that already problematic configuration that was already
        # in place.
        #
        # See https://www.pivotaltracker.com/n/projects/1025368/stories/113569497
        format:
          data_type: text
          facetable: true
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            solr_type: "ssim"
            facet:
              show: false
            search_result:
              show: true
              label: "Format"
              sort_key: 2
            detail:
              show: true
              label: "Format"
              sort_key: 3
        language:
          data_type: text
          facetable: true
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: true
              label: "Language"
              sort_key: 4
            search_result:
              show: true
              label: "Language"
              sort_key: 3
            detail:
              show: true
              label: "Language"
              sort_key: 4
        publisher:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: false
            search_result:
              show: true
              label: "Publisher"
              sort_key: 4
            detail:
              show: true
              label: "Publisher"
              sort_key: 6
        relation:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: false
            search_result:
              show: false
            detail:
              show: true
              label: "Relation"
              sort_key: 14
        rights:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: false
            search_result:
              show: false
            detail:
              show: true
              label: "Rights"
              sort_key: 19
        subject:
          data_type: text
          facetable: true
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: true
              label: "Subject"
              sort_key: 3
            search_result:
              show: false
            detail:
              show: false
        # The format/type field confusion needs to be addressed.  For now we are
        # merely reproducing that already problematic configuration that was already
        # in place.
        #
        # See https://www.pivotaltracker.com/n/projects/1025368/stories/113569497
        type:
          data_type: text
          facetable: true
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: true
              label: "Format"
              sort_key: 1
            search_result:
              show: false
            detail:
              show: true
              label: "Format"
              sort_key: 7
    ichabod:
      info:
        namespace: "NYU::Ichabod::Local"
        uri: "http://library.nyu.edu/data/ichabod#"
      # Optional Fields
      fields:
        addinfolink:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: false
            search_result:
              show: false
            detail:
              show: true
              label: "Additional Information"
              sort_key: 18
              special_handling:
                helper_method: "render_external_links"
                text: "desc_metadata__addinfotext_tesim"
        addinfotext:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            facet:
              solr_type: "tesim"
              show: false
            search_result:
              show: false
            detail:
              show: false
        data_provider:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: false
            search_result:
              show: false
            detail:
              show: true
              label: "Data Provider"
              sort_key: 17
        discoverable:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: false
            search_result:
              show: false
            detail:
              show: false
        geometry:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: false
            search_result:
              show: false
            detail:
              show: false
        isbn:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: false
            search_result:
              show: false
            detail:
              show: true
              label: "ISBN"
              sort_key: 5
        location:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: false
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: false
            search_result:
              show: false
            detail:
              show: true
              label: "Location"
              sort_key: 15
        repo:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: false
          searchable: false
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: false
            search_result:
              show: false
            detail:
              show: true
              label: "Repository"
              sort_key: 16
        resource_set:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: false
          searchable: true
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: false
            search_result:
              show: false
            detail:
              show: false
        subject_spatial:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: false
            search_result:
              show: false
            detail:
              show: false
        subject_temporal:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: false
            search_result:
              show: false
            detail:
              show: false

    nyucore:
      info:
        namespace: "NYU::Nyucore"
        uri: "http://harper.bobst.nyu.edu/data/nyucore#"
        # The above uri needs to be changed to something
        # more official
      fields:
        # Optional Fields
        available:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: false
            search_result:
              show: true
              label: "Online Resource"
              sort_key: 6
              special_handling:
                helper_method: "render_external_links"
                text: "resource_text_display"
            detail:
              show: true
              label: "Online Resource"
              sort_key: 13
              special_handling:
                helper_method: "render_external_links"
                text: "resource_text_display"
        citation:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: false
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: false
            search_result:
              show: false
            detail:
              show: false
        edition:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: false
            search_result:
              show: false
            detail:
              show: false
        restrictions:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: false
          searchable: false
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: false
            search_result:
              show: true
              label: "Access Restrictions"
              sort_key: 5
            detail:
              show: true
              label: "Access Restrictions"
              sort_key: 11
        series:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: false
            search_result:
              show: false
            detail:
              show: true
              label: "Series"
              sort_key: 9
        version:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: false
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: false
            search_result:
              show: false
            detail:
              show: true
              label: "Also available as"
              sort_key: 10
        genre:
          data_type: text
          facetable: false
          indexed: true
          mandatory: false
          multiple: true
          searchable: true
          stored: true
          display:
            solr_type: "tesim"
            facet:
              show: false
            search_result:
              show: false
            detail:
            detail:
              show: true
              label: "Genre"
              sort_key: 12
